version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  backend:
    build: .
    container_name: fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    restart: unless-stopped
    
volumes:
  pgdata:

